# Generated by Django 4.1.7 on 2023-04-03 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=200)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('sem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField()),
                ('expenditure', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('abstract', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('place', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_At', models.DateTimeField(auto_now=True, null=True)),
                ('primary_email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('department', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.usermodel')),
                ('mobile', models.CharField(max_length=200)),
            ],
            bases=('mainapp.usermodel',),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=200)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('receiver', models.ManyToManyField(related_name='receiver', to='mainapp.usermodel')),
                ('sender', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='mainapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subno', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('mode', models.CharField(max_length=200)),
                ('LTP', models.CharField(max_length=200)),
                ('credits', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('session', models.IntegerField()),
                ('prerequisites', models.ManyToManyField(blank=True, null=True, related_name='prerequisites', to='mainapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.usermodel')),
                ('mobile', models.CharField(max_length=200)),
                ('courses', models.ManyToManyField(blank=True, null=True, to='mainapp.course')),
                ('education', models.ManyToManyField(related_name='education', to='mainapp.experience')),
                ('publications', models.ManyToManyField(to='mainapp.publication')),
                ('workex', models.ManyToManyField(related_name='workexperience', to='mainapp.experience')),
            ],
            bases=('mainapp.usermodel',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('usermodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mainapp.usermodel')),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin_code', models.IntegerField(blank=True, null=True)),
                ('backlogs', models.IntegerField(default=0)),
                ('cgpa', models.CharField(default='{"cgpa":["-"]}', max_length=200)),
                ('rollno', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.TextField(default='N/A')),
                ('course', models.CharField(blank=True, default='B.Tech 4Y', max_length=200)),
                ('hall', models.CharField(default='N/A', max_length=200)),
                ('aadhar', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(default='On-Roll', max_length=200)),
                ('EAA', models.CharField(blank=True, max_length=200, null=True)),
                ('adm_year', models.DateField(auto_now=True)),
                ('nationality', models.CharField(default='Indian', max_length=200)),
                ('adm_nature', models.CharField(default='JEE', max_length=200)),
                ('inst_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('teams_pass', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(default='N/A', max_length=200)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('cleared_sem_crd', models.FloatField(default=0)),
                ('sem_crd', models.FloatField(default=0)),
                ('cleared_tot_crd', models.FloatField(default=0)),
                ('tot_crd', models.FloatField(default=0)),
                ('sgpa', models.CharField(default='{"sgpa":["-"]}', max_length=200)),
                ('sem', models.IntegerField(default=1)),
                ('feespaid', models.FloatField(default=0)),
                ('regdone', models.CharField(default='Yes', max_length=10)),
                ('courses', models.ManyToManyField(blank=True, null=True, to='mainapp.course')),
            ],
            options={
                'unique_together': {('rollno', 'adm_year')},
            },
            bases=('mainapp.usermodel',),
        ),
    ]
